[workspace]
authors = ["AurelienT <tollard.aurelien1999@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-mnist"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "==3.12"
mojo = "<1.0.0"
modular = ">=26.2.0.dev2026012605,<27"
